### ISSUE TITLE
AttributeError on context switch

### ISSUE THREAD

**Issue by Lukasa** [rgalanakis/goless#41]
Running 'goless' version 0.7.2 on Windows 7 under PyPy 2.5.0 in some very simple code leads to an `AttributeError` bubbling up out of stackless. The traceback is here:

```
C:\Users\cb2\tmp>pypy golesstest.py
CRITICAL:root:['Traceback (most recent call last):\n', '  File "C:\\pypy-2.5.0-win32\\site-packages\\goless\\__init__.py", line 58, in safe_wrapped\n    f(*args, **kwargs)\n', "TypeError: 'NoneType' object is not callable\n"]
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "golesstest.py", line 37, in <module>
    request_collation(inchan, outchan)
  File "golesstest.py", line 29, in request_collation
    for response in outchan:
  File "C:\pypy-2.5.0-win32\site-packages\goless\channels.py", line 97, in next
    return self._next()
  File "C:\pypy-2.5.0-win32\site-packages\goless\channels.py", line 88, in _next
    return self.recv()
  File "C:\pypy-2.5.0-win32\site-packages\goless\channels.py", line 53, in recv
    got = self._recv()
  File "C:\pypy-2.5.0-win32\site-packages\goless\channels.py", line 153, in _recv
    value = self.waiting_chan.receive()
  File "C:\pypy-2.5.0-win32\site-packages\goless\backends.py", line 79, in receive
    return stackless.channel.receive(self)
  File "C:\pypy-2.5.0-win32\lib_pypy\stackless.py", line 323, in receive
    return self._channel_action(None, -1)
  File "C:\pypy-2.5.0-win32\lib_pypy\stackless.py", line 307, in _channel_action
    schedule()
  File "C:\pypy-2.5.0-win32\lib_pypy\stackless.py", line 524, in schedule
    _scheduler_switch(curr, task)
  File "C:\pypy-2.5.0-win32\lib_pypy\stackless.py", line 150, in _scheduler_switch
    next.switch()
  File "C:\pypy-2.5.0-win32\lib_pypy\stackless.py", line 65, in switch
    current._frame.switch(to=self._frame)
  File "C:\pypy-2.5.0-win32\lib_pypy\stackless.py", line 53, in run
    return func(*argl, **argd)
  File "C:\pypy-2.5.0-win32\lib_pypy\stackless.py", line 415, in _func
    func(*argl, **argd)
  File "C:\pypy-2.5.0-win32\site-packages\goless\__init__.py", line 60, in safe_wrapped
    on_panic(*_sys.exc_info())
  File "C:\pypy-2.5.0-win32\site-packages\goless\__init__.py", line 41, in on_panic
    _be.propagate_exc(SystemExit, 1)
  File "C:\pypy-2.5.0-win32\site-packages\goless\backends.py", line 108, in propagate_exc
    stackless.getmain().throw(errtype, *args)
AttributeError: 'tasklet' object has no attribute 'throw'
```

In practice, this is probably to do with `stackless.py` that PyPy 2.5.0 makes available. In particular, it really does seem not to have the `throw` method.

**Comment by Lukasa** [comment]
If the following method is added to PyPy's `stackless.py` everything seems to work a bit better:

```python
    def throw(self, exc, val=None, tb=None):
        """coro.throw() : throw exception into coroutine"""
        current = _coroutine_getcurrent()
        try:
            current._frame.throw(exc, val=val, tb=tb, to=self._frame)
        finally:
            _tls.current_coroutine = current
```

**Comment by Lukasa** [comment]
It's hard to know, but it feels a bit like this is a PyPy bug more than a goless bug.

**Comment by Lukasa** [comment]
Given [this issue](https://bitbucket.org/pypy/pypy/issue/1826/the-stackless-implementation-of-pypy-is) on PyPy's repo, I think the only question is whether goless should note that currently it does not work with stackless in PyPy.

**Comment by rgalanakis** [comment]
From my discussions with PyPy devs, the stackless.py project is semi-abandoned. They have an earnest interest in fixing things, but generally will only do so with very clear reproduction cases  (this is very understandable, I'm not complaining). And it's not (pro)actively maintained; it ships with PyPy3 and is totally broken.

In theory, if the code works under Stackless, it should work only stackless.py. I would suggest creating a basic test case that works under Stackless but not stackless.py, and opening an issue under PyPy.

On the other hand, if your code breaks under Stackless, that is probably a goless bug!

I will close this, but can reopen it if you find or feel this is something goless can/should fix. I'm not against patching that method into stackless.py if you want to submit a PR (check out https://github.com/rgalanakis/goless/blob/master/goless/backends.py#L69 ).
